#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def _candidate_rows(report: dict[str, Any], build: int) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for row in report["observations"]:
        if row["gameVersion"] != build or row["abilityCatalogName"] is not None:
            continue
        rows.append(
            {
                "hero_name": row["heroName"],
                "hero_catalog_name": row["heroCatalogName"],
                "ability_link": row["abilityLink"],
                "ability_cmd_index": row["abilityCmdIndex"],
                "ability_tag": row["abilityTag"],
                "count": row["count"],
                "replay_count": row["replayCount"],
                "target_types": row["targetTypes"],
            }
        )

    return sorted(
        rows,
        key=lambda item: (
            -item["count"],
            item["hero_name"] or "",
            item["ability_link"],
            item["ability_cmd_index"],
        ),
    )


def _candidate_abilities_by_hero(report: dict[str, Any], build: int) -> dict[str, list[dict[str, str]]]:
    candidates_by_hero: dict[str, list[dict[str, str]]] = {}
    for row in report["observations"]:
        if row["gameVersion"] != build or row["abilityCatalogName"] is not None:
            continue
        hero_catalog_name = row["heroCatalogName"]
        if hero_catalog_name is None or hero_catalog_name in candidates_by_hero:
            continue
        candidates_by_hero[hero_catalog_name] = [
            {
                "catalog_name": candidate["catalogName"],
                "display_name": candidate["displayName"],
            }
            for candidate in row.get("candidateAbilities", ())
        ]
    return dict(sorted(candidates_by_hero.items()))


def _source_metadata(report: dict[str, Any], build: int, rows: list[dict[str, Any]]) -> dict[str, Any]:
    build_observations = [row for row in report["observations"] if row["gameVersion"] == build]
    observed_heroes = sorted({row["heroName"] for row in build_observations if row["heroName"] is not None})
    return {
        "build": build,
        "source": "scripts/replay_ability_report.py --include-candidates",
        "total_replays": report["total"],
        "parsed_replays": report["passed"],
        "failed_replays": report["failed"],
        "build_replays": report["builds"].get(str(build), 0),
        "build_unique_observations": len(build_observations),
        "candidate_rows": len(rows),
        "observed_heroes": len(observed_heroes),
        "note": "Candidate rows are observed replay links plus possible hero catalog abilities; they are not confirmed mappings.",
    }


def _py_string(value: str) -> str:
    return ascii(value)


def _render_candidate_abilities(candidates_by_hero: dict[str, list[dict[str, str]]]) -> str:
    lines = ["{"]
    for hero_catalog_name, candidates in candidates_by_hero.items():
        lines.append(f"    {_py_string(hero_catalog_name)}: (")
        for candidate in candidates:
            lines.append(
                "        AbilityCandidate(%s, %s),"
                % (_py_string(candidate["catalog_name"]), _py_string(candidate["display_name"]))
            )
        lines.append("    ),")
    lines.append("}")
    return "\n".join(lines)


def _render_target_types(target_types: dict[str, int]) -> str:
    items = ", ".join("%s: %d" % (_py_string(key), value) for key, value in sorted(target_types.items()))
    return "{%s}" % items


def _render_link_candidates(rows: list[dict[str, Any]]) -> str:
    lines = ["("]
    for row in rows:
        lines.append(
            "    AbilityLinkCandidate(%s, %s, %d, %d, %d, %d, %d, %s),"
            % (
                _py_string(row["hero_name"]),
                _py_string(row["hero_catalog_name"]),
                row["ability_link"],
                row["ability_cmd_index"],
                row["ability_tag"],
                row["count"],
                row["replay_count"],
                _render_target_types(row["target_types"]),
            )
        )
    lines.append(")")
    return "\n".join(lines)


def render_module(report: dict[str, Any], build: int) -> str:
    rows = _candidate_rows(report, build)
    candidates_by_hero = _candidate_abilities_by_hero(report, build)
    metadata = _source_metadata(report, build, rows)
    metadata_json = json.dumps(metadata, ensure_ascii=True, indent=4)
    return (
        "from __future__ import annotations\n\n"
        "from typing import NamedTuple\n\n\n"
        "# Generated by scripts/generate_ability_link_candidates.py.\n"
        "# Do not treat this file as confirmed ability mappings.\n"
        "# A row means that a replay observed this numeric ability link for the hero;\n"
        "# HERO_ABILITY_CANDIDATES lists possible catalog abilities for that hero.\n\n\n"
        "class AbilityCandidate(NamedTuple):\n"
        "    catalog_name: str\n"
        "    display_name: str\n\n\n"
        "class AbilityLinkCandidate(NamedTuple):\n"
        "    hero_name: str\n"
        "    hero_catalog_name: str\n"
        "    ability_link: int\n"
        "    ability_cmd_index: int\n"
        "    ability_tag: int\n"
        "    count: int\n"
        "    replay_count: int\n"
        "    target_types: dict[str, int]\n"
        "\n\n"
        f"ABILITY_LINK_CANDIDATE_SOURCE_{build}: dict[str, object] = {metadata_json}\n\n\n"
        f"HERO_ABILITY_CANDIDATES_{build}: dict[str, tuple[AbilityCandidate, ...]] = "
        f"{_render_candidate_abilities(candidates_by_hero)}\n\n\n"
        f"ABILITY_LINK_CANDIDATES_{build}: tuple[AbilityLinkCandidate, ...] = {_render_link_candidates(rows)}\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("report_json", type=Path)
    parser.add_argument("--build", type=int, default=97039)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args(argv)

    report = json.loads(args.report_json.read_text(encoding="utf-8"))
    args.out.write_text(render_module(report, args.build), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
